sudo: false

language: android
jdk: oraclejdk8

android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
- chmod +x gradlew

script:
- "./gradlew clean assembleDebug -PdisablePreDex --stacktrace"
- ls
