sudo: false

language: android
jdk: oraclejdk8

android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26


before_install:
- chmod +x gradlew

script:
- "./gradlew clean assembleDebug -PdisablePreDex --stacktrace"
- cd build/android-profile
- ls
